# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
<body>
    <div class="head">
        <div class="header" style="display:flex;    justify-content: space-between; align-items: center">
            <div style="    height: auto;
    margin-top: 5px;
    padding-top: 0px;
    padding-bottom: 0px;
    padding-left: 20px;
    font-size: 21px;
    font-weight: 700;
    color: rgb(255, 255, 255);
    position: relative;
    z-index: 1;"><a class="logo" href="a.bee grand store.html">
                    <img src="brands/apple.svg" alt="home"
                        style="margin-top: 7px; width: 16px; padding-left: 15px; padding-right: 15px; margin: 0px; position: relative; z-index: 1;">
                    a.bee grand store
                </a>
            </div>
            <a>
                <svg id="w" class="svg" viewBox="0 0 22 14.46">
                    <path d="M0 0h22v1.99H0zm0 6.24h22v1.99H0zm0 6.23h22v1.99H0z"></path>
                </svg>
            </a>
        </div>
        <a href="a.bee grand store.html"><button class="button" type="button"></button></a>
        <a>
        </a>
        <ol class="first"><a>
            </a>
            <li><a>
                </a><a id="w" href="clothes.html" title="go to clothes shop" target="_blank">clothes</a>
            </li>
            <li>
                <a id="w" href="apparatues.html" title="go to apparatues shop" target="_blank">apparatues</a>
            </li>
            <li>
                <a id="w" href="furniture.html" title="go to furniture shop" target="_blank">furniture</a>
            </li>
            <li>
                <a id="w" href="nutritive items.html" title="go to nutritive items shop" target="_blank">nutritive
                    items</a>
            </li>
            <li>
                <a href="a.bee-index.html" title="go back home" target="_blank">home</a>
            </li>
        </ol>

    </div>
    <img class="baground" src="images/13613998864.jpg" alt="">
    <footer>
        <img class="foterimg" src="images/RE4wpof.jpg" alt="">
    </footer>


</body>
